name: Yarn

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install

    - name: Lint
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: lint

    - name: Style lint
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: style:lint

    - name: Build
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build
